version: '3.1'

volumes:
  redmine-plugins:
  redmine-themes:
  redmine-data:

services:

  redmine:
    # image: redmine:4.0
    build:
      context: .
      dockerfile: Dockerfile-plugins
    restart: always
    ports:
      - 8181:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    volumes:
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-themes:/usr/src/redmine/public/themes
      - redmine-data:/usr/src/redmine/files

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
